[widgets]
button_box    = "iced::widget::button, iced::widget::text, iced::{Length, Border, Vector, Shadow}"
button        = "iced::widget::button, iced::widget::text, iced::{Length, Border, Vector, Shadow}"
checkbox      = "iced::widget::checkbox, iced::widget::text, iced::Length"
column        = "iced::widget::column, iced::{Length, Padding, Alignment}"
container     = "iced::widget::container, iced::{Length, Padding, Alignment, Color}"
h_rule        = "iced::widget::rule, iced::Length"
image         = "iced::widget::{image, image::FilterMethod}, iced::{ContentFit, Degrees, Element, Length, Rotation, Theme}, iced::advanced::mouse::Event"
mouse_area    = "iced::widget::mouse_area, iced::advanced::mouse::Event"
pick_list     = "iced::widget::{pick_list, text}, iced::{Length, Pixels}"
progress_bar  = "iced::widget::progress_bar, iced::Length"
qr_code       = "iced::widget::qr_code, iced::widget::qr_code::Data"
radio         = "iced::widget::radio, iced::Length"
row           = "iced::widget::row, iced::{Length, Padding, Alignment}"
scrollable    = "iced::widget::scrollable"
slider        = "iced::widget::slider, iced::Length, ordered_float::OrderedFloat"
space         = "iced::widget::space, iced::Length"
stack         = "iced::widget::stack, iced::{Length, Alignment}"
svg           = "iced::widget::svg, iced::widget::svg::Handle, iced::{Length, Pixels}"
text_input    = "iced::widget::text_input, iced::Length"
text          = "iced::widget::text, iced::widget::text::{Wrapping, Shaping}, iced::{Length, Color, Font}"
toggler       = "iced::widget::toggler, iced::Length"
v_rule        = "iced::widget::rule, iced::Length"
